//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WecDonald_s歡樂送
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public members()
        {
            this.carts = new HashSet<carts>();
        }
    
        public int mId { get; set; }
        public string mName { get; set; }
        public string mAddr { get; set; }
        public string email { get; set; }
        public System.DateTime birthday { get; set; }
        public string mTel { get; set; }
        public string password { get; set; }
        public int permission { get; set; }
        public int points { get; set; }
        public int cash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carts> carts { get; set; }
    }
}
